theme: jekyll-theme-slate
lang:  pt-PT
show_downloads: no
title: Experiência e Acessibilidade Digital
description: A equipa de Experiência e Acessibilidade Digital (EAD é uma equipa da Agência para a Reforma Tecnológica do Estado (ARTE I.P.) desenvolve e monitoriza serviços públicos digitais, cuidando para que os mesmos sigam os mais altos padrões de usabilidade e de acessibilidade. 
