theme: jekyll-theme-slate
lang:  pt-PT
show_downloads: no
title: Experiência e Acessibilidade Digital
description: Conformidade dos serviços em linha da AP Portuguesa para com os _standards_ de usabilidade e de acessibilidade
